/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../lib/print-document-stamp`; params?: Router.UnknownInputParams; } | { pathname: `/../../components/DocumentStatusStamp`; params?: Router.UnknownInputParams; } | { pathname: `/../../.next/types/validator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/commitments` | `/reports/commitments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/daily-sales-summary` | `/reports/daily-sales-summary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/stock-inquiry` | `/reports/stock-inquiry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/stock-vs-commitments` | `/reports/stock-vs-commitments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/validation` | `/validation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../../lib/print-document-stamp`; params?: Router.UnknownOutputParams; } | { pathname: `/../../components/DocumentStatusStamp`; params?: Router.UnknownOutputParams; } | { pathname: `/../../.next/types/validator`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reports/commitments` | `/reports/commitments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reports/daily-sales-summary` | `/reports/daily-sales-summary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reports/stock-inquiry` | `/reports/stock-inquiry`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reports/stock-vs-commitments` | `/reports/stock-vs-commitments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/validation` | `/validation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../../lib/print-document-stamp${`?${string}` | `#${string}` | ''}` | `/../../components/DocumentStatusStamp${`?${string}` | `#${string}` | ''}` | `/../../.next/types/validator${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reports/commitments${`?${string}` | `#${string}` | ''}` | `/reports/commitments${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reports/daily-sales-summary${`?${string}` | `#${string}` | ''}` | `/reports/daily-sales-summary${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reports/stock-inquiry${`?${string}` | `#${string}` | ''}` | `/reports/stock-inquiry${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reports/stock-vs-commitments${`?${string}` | `#${string}` | ''}` | `/reports/stock-vs-commitments${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/validation${`?${string}` | `#${string}` | ''}` | `/validation${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../lib/print-document-stamp`; params?: Router.UnknownInputParams; } | { pathname: `/../../components/DocumentStatusStamp`; params?: Router.UnknownInputParams; } | { pathname: `/../../.next/types/validator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/commitments` | `/reports/commitments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/daily-sales-summary` | `/reports/daily-sales-summary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/stock-inquiry` | `/reports/stock-inquiry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports/stock-vs-commitments` | `/reports/stock-vs-commitments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/validation` | `/validation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
